# Example .coderabbit.yaml
language: "en-US"
reviews:
  profile: "chill" # Options: chill, assertive, etc.
  request_changes_workflow: false
  high_level_summary: true
# Prevent AI from reviewing specific paths
path_filters:
  - "!dist/**"
  - "!node_modules/**"
